name: JWebMP Plugins
on:
  workflow_dispatch:
    inputs:
      centralRelease:
        type: boolean
        description: Run a release to maven central
        default: false
  push:
env:
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
permissions:
  contents: read
  packages: write
jobs:
  TypescriptClient:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'TypescriptClient/'
      name: 'Typescript Client'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  Angular:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - TypescriptClient
    with:
      baseDir: 'Angular/'
      name: 'Angular'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  EasingEffects:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - TypescriptClient
    with:
      baseDir: 'EasingEffects/'
      name: 'Easing Effects'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  Globalize:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - TypescriptClient
    with:
      baseDir: 'Globalize/'
      name: 'Globalize'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  JQuery:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - TypescriptClient
    with:
      baseDir: 'JQuery/'
      name: 'JQuery'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  Modernizr:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - TypescriptClient
    with:
      baseDir: 'Modernizr/'
      name: 'Modernizr'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  PlusAsTab:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - TypescriptClient
    with:
      baseDir: 'PlusAsTab/'
      name: 'PlusAsTab'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  Prettify:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: 'Prettify/'
      name: 'Prettify'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  Moment:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - TypescriptClient
    with:
      baseDir: 'Moment/'
      name: 'Moment'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  LocalStorage:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - TypescriptClient
    with:
      baseDir: 'LocalStorage/'
      name: 'LocalStorage'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  SessionStorage:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - TypescriptClient
    with:
      baseDir: 'SessionStorage/'
      name: 'SessionStorage'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  Toastr:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - EasingEffects
      - JQuery
    with:
      baseDir: 'Toastr/'
      name: 'Toastr'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  WayPoints:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - TypescriptClient
    with:
      baseDir: 'WayPoints/'
      name: 'WayPoints'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  JQueryUI:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - EasingEffects
      - Globalize
      - JQuery
    with:
      baseDir: 'JQueryUI/'
      name: 'JQueryUI'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
  Bootstrap:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    needs:
      - Moment
      - TypescriptClient
      - Angular
    with:
      baseDir: 'Bootstrap/'
      name: 'Bootstrap'
      publishToCentral: ${{inputs.centralRelease}}
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}